# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='unlike',
        ),
        migrations.AddField(
            model_name='like',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
